resources:
- busybox-dc-21.yaml
- busybox-pvc-21.yaml
- busybox-dc-22.yaml
- busybox-pvc-22.yaml
- busybox-dc-23.yaml
- busybox-pvc-23.yaml
- busybox-dc-24.yaml
- busybox-pvc-24.yaml
- busybox-dc-25.yaml
- busybox-pvc-25.yaml
