resources:
- busybox-dc-41.yaml
- busybox-pvc-41.yaml
- busybox-dc-42.yaml
- busybox-pvc-42.yaml
- busybox-dc-43.yaml
- busybox-pvc-43.yaml
- busybox-dc-44.yaml
- busybox-pvc-44.yaml
- busybox-dc-45.yaml
- busybox-pvc-45.yaml
- busybox-dc-46.yaml
- busybox-pvc-46.yaml
- busybox-dc-47.yaml
- busybox-pvc-47.yaml
- busybox-dc-48.yaml
- busybox-pvc-48.yaml
- busybox-dc-49.yaml
- busybox-pvc-49.yaml
- busybox-dc-50.yaml
- busybox-pvc-50.yaml
- busybox-dc-51.yaml
- busybox-pvc-51.yaml
- busybox-dc-52.yaml
- busybox-pvc-52.yaml
- busybox-dc-53.yaml
- busybox-pvc-53.yaml
- busybox-dc-54.yaml
- busybox-pvc-54.yaml
- busybox-dc-55.yaml
- busybox-pvc-55.yaml
- busybox-dc-56.yaml
- busybox-pvc-56.yaml
- busybox-dc-57.yaml
- busybox-pvc-57.yaml
- busybox-dc-58.yaml
- busybox-pvc-58.yaml
- busybox-dc-59.yaml
- busybox-pvc-59.yaml
- busybox-dc-60.yaml
- busybox-pvc-60.yaml
commonLabels:
  app-name: app-busybox-rbd-3
