resources:
- data-viewer_all.yaml
- mysql.yaml
- mysql_pvc.yaml
- mysql_service.yaml
- io_writer_mysql.yaml
- mysql_secret.yaml
- busybox-dc-81.yaml
- busybox-pvc-81.yaml
- busybox-dc-82.yaml
- busybox-pvc-82.yaml
- busybox-dc-83.yaml
- busybox-pvc-83.yaml
- busybox-dc-84.yaml
- busybox-pvc-84.yaml
- busybox-dc-85.yaml
- busybox-pvc-85.yaml
- busybox-dc-86.yaml
- busybox-pvc-86.yaml
- busybox-dc-87.yaml
- busybox-pvc-87.yaml
- busybox-dc-88.yaml
- busybox-pvc-88.yaml
- busybox-dc-89.yaml
- busybox-pvc-89.yaml
- busybox-dc-90.yaml
- busybox-pvc-90.yaml
- busybox-dc-91.yaml
- busybox-pvc-91.yaml
- busybox-dc-92.yaml
- busybox-pvc-92.yaml
- busybox-dc-93.yaml
- busybox-pvc-93.yaml
- busybox-dc-94.yaml
- busybox-pvc-94.yaml
- busybox-dc-95.yaml
- busybox-pvc-95.yaml
- busybox-dc-96.yaml
- busybox-pvc-96.yaml
- busybox-dc-97.yaml
- busybox-pvc-97.yaml
- busybox-dc-98.yaml
- busybox-pvc-98.yaml
- busybox-dc-99.yaml
- busybox-pvc-99.yaml
- busybox-dc-100.yaml
- busybox-pvc-100.yaml
