resources:
- busybox-dc-1.yaml
- busybox-dc-2.yaml
- busybox-dc-3.yaml
- busybox-dc-4.yaml
- busybox-pvc-1.yaml
- busybox-pvc-2.yaml
- busybox-pvc-3.yaml
- busybox-pvc-4.yaml
commonLabels:
  app-name: app-busybox-cephfs-2
