apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/fb-configmap.yaml
- base/fb-deployment-client.yaml
- base/fb-deployment-server.yaml
- base/fb-route.yaml
- base/fb-service.yaml
- base/filebrowser-pvc.yaml
