resources:
- busybox-dc-1.yaml
- busybox-pvc-1.yaml
- busybox-dc-2.yaml
- busybox-pvc-2.yaml
- busybox-dc-3.yaml
- busybox-pvc-3.yaml
- busybox-dc-4.yaml
- busybox-pvc-4.yaml
- busybox-dc-5.yaml
- busybox-pvc-5.yaml
- busybox-dc-6.yaml
- busybox-pvc-6.yaml
- busybox-dc-7.yaml
- busybox-pvc-7.yaml
- busybox-dc-8.yaml
- busybox-pvc-8.yaml
- busybox-dc-9.yaml
- busybox-pvc-9.yaml
- busybox-dc-10.yaml
- busybox-pvc-10.yaml
commonLabels:
  app-name: app-busybox-cephfs-3
